spring:
  application:
    name: bookstore-api

server:
  port: 8000
  forward-headers-strategy: framework

logging:
  level:
    http.logger.full: DEBUG
    http.logger.error: ERROR
  pattern:
    console: "%msg%n"  # 关键：只输出消息内容，不添加时间戳等前缀
