name: tom-demo-cicd-pipeline

on:
  push:
    branches:
      - main     # 自动部署到 dev
  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - dev

concurrency:
  group: ${{ github.ref }}-1
  cancel-in-progress: true

env:
  AWS_REGION: ap-east-1
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build[${{ github.event.inputs.env || 'dev' }}]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B -ntp clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t app:${IMAGE_TAG} .

      - name: Save Docker image
        run: |
          docker save app:${IMAGE_TAG} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  push-image:
    name: Push Image (Requires Approval)
    needs: [ build ]
    runs-on: ubuntu-latest

    environment:
      name: approval-${{ github.event.inputs.env || 'dev' }}

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i image.tar
      - name: print variable
        run: echo "AWS_ROLE=${{ vars.AWS_ROLE }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and Push image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker tag app:${IMAGE_TAG} $IMAGE_URI
          docker push $IMAGE_URI